name: Build and Test Astarte Housekeeping

on:
  # Run when pushing to stable branches
  push:
    paths:
    - 'apps/astarte_housekeeping/**'
    - '.github/workflows/astarte-apps-build-workflow.yaml'
    - '.github/workflows/astarte-housekeeping-workflow.yaml'
    branches:
    - 'master'
    - 'release-*'
  # Run on branch/tag creation
  create:
  # Run on pull requests for astarte_housekeeping
  pull_request:
    paths:
    - 'apps/astarte_housekeeping/**'
    - '.github/workflows/astarte-apps-build-workflow.yaml'
    - '.github/workflows/astarte-housekeeping-workflow.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  astarte_housekeeping:
    uses: ./.github/workflows/astarte-apps-build-workflow.yaml
    with:
      app: "astarte_housekeeping"
    secrets: inherit
